### ISSUE TITLE
Which config would match the result of 6-7 coremark/Mhz

### ISSUE THREAD

**Issue by pengwubj** [chipsalliance/Cores-SweRV-EH2#14]
I have tried running coremark_mt with configuration of high_perf and  typical_pd， but I only got results of 3.5 to 3.6 /MHz. 
 But as this paper(https://www.westerndigital.com/company/innovations/risc-v) says, the max perf of  coremark is 7.8. Could you   show me the config to get same perf ? Or, this opensource version is different from the one in WD website.

**Comment by agrobman** [comment]
if you run 

make -f $RV_ROOT/tools/Makefile verilator target=default_mt TEST=cmark_dccm_mt

you should get following result:
```

DCCM pre-load from f0040000 to f0043580
2K performance run parameters for coremark.
CoreMark Size    : 666
Total ticks      : 334913
Total time (secs): 334
Iterat/Sec/MHz   **: 5.98** <<<<<<<<<<<<
Iterations       : 2
Compiler version : GCC9.2.0
Compiler flags   : -g -O3 -funroll-all-loops 
Memory location  : STATIC
seedcrc          : 0xe9f5
[0]crclist       : 0xe714
[0]crcmatrix     : 0x1fd7
[0]crcstate      : 0x8e3a
[0]crcfinal      : 0xe714
Correct operation validated. See readme.txt for run and reporting rules.
TEST_PASSED
```
to get higher scores you need to play with compiler switches ...

**Comment by pengwubj** [comment]
Thanks a lot. I have replayed the results.
