### ISSUE TITLE
Add cmark.hex

### ISSUE THREAD

**Issue by wsnyder** [chipsalliance/Cores-SweRV-EH2#2]
Please provide allowing running the cmark test without requiring the tool chain.

I suggest someone build cmark's hex files, and commit them under testbench/cmark.hex/program.hex and testbench/cmark.hex/data.hex.

We can then run with "make .... TEST=cmark.hex"

Which is the new pull #1 syntax. Thanks

**Comment by aprnath** [comment]
This was done via commit 7e13a593d7be43a6bf61ec60c12e9a5f1fc309c1
