### ISSUE TITLE
understanding store_databypass_c1 and c2

### ISSUE THREAD

**Issue by vignajeth** [chipsalliance/Cores-SweRV-EH2#25]
Hi,
   I am trying to understand how _store_data_bypass_c1_ and _store_data_bypass_c2_ signal helps in forwarding data. 
I took a simple RAW hazard scenario as below and only one thread is executing this in order.
```
  lw X13, 23(X10);
  sw X13, 32(X11);
```
when the `sw` instruction is in decode stage the _store_data_bypass_c2_ should become high.
the LSU dc1 to dc3 stages for the two instruction should be like
```
LW LW LW
   SW SW
```
and from the code of lsu I can understand that when `sw` instruction is executed in lsu,  _store_data_dc2_ gets overwritten with _lsu_result_dc3_ data. which is basically forwarding `lw` data 

but this is a best case scenario since the previous `lw` instruction should have obtained data in dc3 either through lsu_buffer or from a forwarding logic.

My question here is if the previous `lw`  data was not in buffer, it should take 5 or 6 CC to get data from the main memory, then this `sw` instruction should be stalled for few cycles, but i don't think this stall happens or there is some other way the core takes care of this situation.

it would be great if someone can help me fill my missing piece of insight.

**Comment by vignajeth** [comment]
i solved a bit of my issue
i can notice stall happening in the decoder stage, however, another interesting thingIi notice is the instruction buffer reissues `sw` instruction if it pushes out both `lw` and `sw`  at a same cycle previously 
i can understand why the `SW` instruction is issued again, but, somehow the instbuf is smart enough to do it,  i am curious to know how this scenario happens

**Comment by aprnath** [comment]
There is only one load/store unit - so only L/S op can be issued per cycle. The decode unit provides the stall for this resource hazard.

**Comment by vignajeth** [comment]
```  assign i1_load2_block_d = i1_dp.lsu & i0_dp.lsu;``` 
 👍
