### ISSUE TITLE
Hardware Accelerator and its interface.

### ISSUE THREAD

**Issue by zeeshanrafique23** [chipsalliance/Cores-SweRV-EH2#5]
Is there any hardware accelerator and interface for SweRV32-EH2, if yes please let me know. 
Or is there any hardware optimization available in the core for AI/ML?
I had posted this question in [Core-WG](https://lists.chipsalliance.org/g/cores-wg/message/2) but no one is there to respond me back.

**Comment by aprnath** [comment]
Hi,
There are no accelerator interfaces available for EH2 at the moment. This (and AI/ML) is an interesting topic and if you wish to start,  and participate in, such a conversation please engage with the Core-WG. That is an appropriate forum to discuss enhancements and use cases for these cores.
Thanks!
