### ISSUE TITLE
AHB-Lite support

### ISSUE THREAD

**Issue by qq27303272** [chipsalliance/Cores-SweRV-EH2#6]
the EN2 RTL code already include AHB-lite ports,  why doc metioned that it is not support ?

**Comment by agrobman** [comment]
EH2 design does no support AHB buses. The CPU designed with busses, supporting AXI4 protocol.

**Comment by qq27303272** [comment]
> EH2 design does no support AHB buses. The CPU designed with busses, supporting AXI4 protocol.

why not consider to support AHB-Lite？

**Comment by agrobman** [comment]
you can try to use it, but we never verified it worked. ( -set build_ahb_lite for swerv.config script)
