### ISSUE TITLE
Verilator build is erroring out

### ISSUE THREAD

**Issue by irfanwaheed** [chipsalliance/Cores-SweRV-EH2#7]
I ran this on a clean checkout:
make -f $RV_ROOT/tools/Makefile target=default_mt debug=1

I am getting the following error:
VerilatorTB: Start of sim

terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
/home/user/swerv_eh2/Cores-SweRV-EH2/tools/Makefile:113: recipe for target 'verilator' failed
make: *** [verilator] Aborted (core dumped)

**Comment by irfanwaheed** [comment]
Sorry need to try with latest verilator. I had 3.916

**Comment by zhuanshulz** [comment]
so do u know how to solve this problem ?
